- name: Add the ansible user
  user:
    name: ansible
    group: sudo
    generate_ssh_key: yes
    shell: /bin/bash
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: ansible_user

- stat: path=/home/ansible/.ssh/authorized_keys
  register: authorized

- name: authorize ssh key
  copy:
    remote_src: yes
    src: /home/ansible/.ssh/id_rsa.pub
    dest: /home/ansible/.ssh/authorized_keys
    mode: 600
    owner: ansible
    owner: ansible

- name: install codebase
  git:
     repo: https://bitbucket.org/automationlogic/ubuntu_build.git
     dest: /home/ansible/ansible
     update: yes

- name: disable ipv6 disable ipv6 in grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash .*"'
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash ipv6.disable=1"

- name: disable ipv6 in grub 2
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=".*"'
    line: GRUB_CMDLINE_LINUX="ipv6.disable=1"

- name: install chrome ansible galaxy 
  command: ansible-galaxy install darkwizard242.googlechrome
  creates: /home/ansible/.ansible/roles/darkwizard242.googlechrome/LICENSE
  become_user: ansible



 
- name: install slack ansible galaxy 
  command: ansible-galaxy install oefenweb.slack
  creates: /home/ansible/.ansible/roles/oefenweb.slack/LICENSE.txt
  become_user: ansible

- name: run ansible 
  cron:
    name: "run ansible"
    minute: "*"
    hour: "*"
    user: ansible
    job: "ansible-playbook /home/ansible/ansible/site.yml > /home/ansible/ansible.log"


